# Movie review Sentiment Analytics

In [43]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from imblearn.metrics import sensitivity_specificity_support
from sklearn.naive_bayes import BernoulliNB

Using TensorFlow backend.


In [14]:
'''
    Loading the datasets
'''


amazon = "C:/Users/91973/Desktop/Upgrad/Machine Learning/Sentiment Analytics/sentiment labelled sentences/amazon_cells_labelled.txt"
imdb = "C:/Users/91973/Desktop/Upgrad/Machine Learning/Sentiment Analytics/sentiment labelled sentences/imdb_labelled.txt"
yelp = "C:/Users/91973/Desktop/Upgrad/Machine Learning/Sentiment Analytics/sentiment labelled sentences/yelp_labelled.txt"

with open(amazon,'r') as text_file:
    lines = text_file.read().split("\n")
print("Lines loaded", len(lines))
with open(imdb,'r') as text_file:
    lines += text_file.read().split("\n")
print("Lines loaded", len(lines))
with open(yelp,'r') as text_file:
    lines += text_file.read().split("\n")
print("Lines loaded", len(lines))

Lines loaded 1001
Lines loaded 2002
Lines loaded 3003


In [18]:
lines = [line.split("\t") for line in lines if len(line.split("\t"))==2 and line.split("\t")[1] != '']

In [37]:
X = [line[0] for line in lines]
y = [int(line[1]) for line in lines]

In [38]:
'''
    Converting the `reviews` to vectorized form
'''
count_vectorizer = CountVectorizer(binary=True)
X = count_vectorizer.fit_transform(X)

In [39]:
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size=0.7,test_size=0.3,random_state=0)

In [41]:
nb = BernoulliNB()
nb.fit(X_train,y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [42]:
y_pred = nb.predict(X_test)

In [45]:
# create onfusion matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

# check sensitivity and specificity
sensitivity, specificity, _ = sensitivity_specificity_support(y_test, y_pred, average='binary')
print("Sensitivity: \t", round(sensitivity, 2), "\n", "Specificity: \t", round(specificity, 2), sep='')


[[376  69]
 [107 348]]
Sensitivity: 	0.76
Specificity: 	0.84


In [55]:
nb.predict(count_vectorizer.transform(["Its the worst movie"]))

array([0])

In [56]:
nb.predict(count_vectorizer.transform(["Its the best movie"]))

array([1])

In [57]:
nb.predict(count_vectorizer.transform(["screenplay is awesome"]))

array([1])

In [58]:
nb.predict(count_vectorizer.transform(["screenplay is pathetic"]))

array([0])